### ISSUE TITLE
Opencv error

### ISSUE THREAD

**Issue by maria364** [drejkim/face-detection-node-opencv#2]
I downloaded your code on my ubuntu 12.04. I try to compile and run it by following your instructions. 
I have installed node.js, opencv, npm and xampp. 

When i run the server "node server.js" and try to connect from localhost, i get no image and after some seconds, i get the error below:

"Opencv Error: Bad flag (parameter or structure field) (Unrecignized or unsupported array type) in cvGetMat

terminate called after throwing an instance of 'cv:Exception'  "

Could you please help me?

**Comment by estherjk** [comment]
Which version of OpenCV do you have installed?

**Comment by maria364** [comment]
i've installed opencv-2.4.10.

**Comment by estherjk** [comment]
Hmm, can it be related to this issue: https://github.com/peterbraden/node-opencv/issues/261? Can you modify `server/lib/routes/socket.js` with the `writeLock` workaround to see if this resolves your error?

**Comment by werdnanoslen** [comment]
I'm also experiencing this error, running opencv-2.4.10. The camera works fine, tested via raspivid.
Code is at https://github.com/werdnanoslen/funberry

**Comment by estherjk** [comment]
Resolved with https://github.com/drejkim/face-detection-node-opencv/commit/c817bb54f94aeed526f39acbc3a51df414fa33d1.
