### ISSUE TITLE
cannot view the video on localhost

### ISSUE THREAD

**Issue by harshmunshi** [drejkim/face-detection-node-opencv#6]
Hi the code is running fine without errors but I cannot see anything on my local host. There is just a box and that;s it. Need help

I am using opencv 3.1

**Comment by estherjk** [comment]
I haven't tested with OpenCV 3.1, so not sure if it works. Can you also check if there are any error messages that you see in the web browser console? Also, which browser / OS are you using?

**Comment by harshmunshi** [comment]
Hi I downgraded to opencv 2.4.12 and it works fine.
